### ISSUE TITLE
Upgrade MastodonList class?

### ISSUE THREAD

**Issue by michelc** [glacasa/Mastonet#94]
Now that the properties of the ArrayOptions class have been transformed from `long` to `string`, shouldn't the `NextPageMaxId`, `PreviousPageSinceId` and `PreviousPageMinId` properties of the `MastodonList` class also be changed?

I can try to code it if you think it should be done.

**Comment by glacasa** [comment]
Exactly, it should be updated.
I already have the project open, I'm on it ! Thanks

I also want to add methods (either on the MastodonList or on the client with the MastodonList as parameter) to get the next/prev page, instead of using the ArrayOptions - it's something I have thought about for some time…

**Comment by michelc** [comment]
Super ! Can I close the ticket then?

**Comment by glacasa** [comment]
I usually post a message when the fix is on nuget, but you can close it if you want ;)
